<!DOCTYPE html>
<html lang="zh">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>预言家系统</title>
		<link rel="stylesheet" type="text/css" href="/css/base.css"/>
		<link rel="stylesheet" type="text/css" href="/css/default.css">
	    <link rel="shortcut icon" type="image/x-icon" href="/images/logo.png"/>
		<!--必要样式-->
		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<link rel="stylesheet" type="text/css" href="/css/laydate.css"/>
		<link rel="stylesheet" type="text/css" href="/css/skin.css"/>
		<link rel="stylesheet" type="text/css" href="/css/loading.css"/>
		<!--<link rel="stylesheet" href="css/demo.css">-->
    	<script src="/js/iconfont.js"></script>
    	<script type="text/javascript" charset="utf-8" src="/js/laydate.js"></script> <!-- iconfont -->
		<style type="text/css">
	        .icon {
	          /* 通过设置 font-size 来改变图标大小 */
	          width: 1em; height: 1em;
	          /* 图标和文字相邻时，垂直对齐 */
	          vertical-align: -0.15em;
	          /* 通过设置 color 来改变 SVG 的颜色/fill */
	          fill: currentColor;
	          /* path 和 stroke 溢出 viewBox 部分在 IE 下会显示
	             normalize.css 中也包含这行 */
	          overflow: hidden;
	        }
	
	    </style>
		<script type="text/javascript" charset="utf-8" src="/js/jquery-2.1.1.min.js"></script>
		<script type="text/javascript" src="/js/d3.v4.min.js"></script>
                <script src="/js/jquery.cookie.js"></script>
                <script>
                    var c = null;
                </script>
	</head>
	<body>
		<div class="index-container">
			<!--header start-->
			<header class="clearfix" style="box-shadow: 0px -2px 26px -5px #607D8B;">
				<h3 class="title-logo">
					<img src="images/logo.png"/>
					<i style="vertical-align: super;">预言家系统</i>
				</h3>
				<ul class="in_right login">
					<li>
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-yonghu"></use>
	                    </svg>
					</li>
					<li>用户:</li>
					<li class="login_one "><a href="javascript:;" id="userName"></a></li>
					<li><a href="javascript:;" id="Logout" onclick="exit()">退出登录</a></li>
				</ul>
			</header>
			<!--header end-->
			<!--LeftBox start-->
			<aside class="index-leftBox navItems">
				<ul class="mainmenu">
					<li id="105">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-dingqi"></use>
	                    </svg>
						<span>定期到期</span>
					</li>
					<li id="106">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-quedingduihuan"></use>
	                    </svg>
						<span>兑付</span>
					</li>
					<li id="107">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-shuhui"></use>
	                    </svg>
						<span>活期赎回</span>
					</li>
					<li id="108">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-lvqiatonghuoqizhuandingqi"></use>
	                    </svg>
						<span>活包定到期</span>
					</li>
					<li id="109">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-shichang"></use>
	                    </svg>
						<span>二级市场到期</span>
					</li>
					<li id="110">
						<svg class="icon" aria-hidden="true">
	                        <use xlink:href="#icon-demo15"></use>
	                    </svg>
						<span>新交易用户</span>
					</li>
				</ul>
			</aside>
			<!--LeftBox end-->
			<!--RightBox strat-->
			<aside class="index-rightBox"></aside>
		    <!--RightBox end-->
		</div>
		<!-- 日期选项 -->
        <div id="date-query">
            <form >
            	<section class="submenu">
	                <input type="text" value="" placeholder="请输入到期开始日期" onClick="c = laydate({istime: true, format: 'YYYY-MM-DD'})">
	            	<input type="text" value="" placeholder="请输入到期结束日期" onClick="laydate({istime: true, format: 'YYYY-MM-DD'})">
	                <hr />
	                <input type="text" value="" placeholder="请输入跟踪开始时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})">
	            	<input type="text" value="" placeholder="请输入跟踪结束时间" class="laydate-icon" onClick="laydate({istime: true, format: 'YYYY-MM-DD hh:mm:ss'})">
	            </section>
                <input type="button" value="提交" class="submit" style="cursor: pointer;"/>
            </form>
        </div>
        <div id="overText"><!-- 详细类数据显示 金额&人数  --></div>
	</body>
	<script type="text/javascript" charset="utf-8" src="/js/echarts.js"></script>
	<script type="text/javascript" charset="utf-8" src="/js/baseStyle.js"></script>
	<script type="text/javascript" charset="utf-8" src="/js/submit.js"></script>
	<script type="text/javascript">
		var dataUser = $.cookie('US_SESSION_ID'); 
		$('#userName').html($.cookie('fuser'));
		!function(){
			laydate.skin('molv');//切换皮肤，请查看skins下面皮肤库
			laydate({elem: '#demo'});//绑定元素
		}();
	
		//日期范围限制
		var start = {
		    elem: '#start',
		    format: 'YYYY-MM-DD',
		    min: laydate.now(), //设定最小日期为当前日期
		    max: '2099-06-16', //最大日期
		    istime: true,
		    istoday: false,
		    choose: function(datas){
		         end.min = datas; //开始日选好后，重置结束日的最小日期
		         end.start = datas //将结束日的初始值设定为开始日
		    }
		};
		var end = {
		    elem: '#end',
		    format: 'YYYY-MM-DD',
		    min: laydate.now(),
		    max: '2099-06-16',
		    istime: true,
		    istoday: false,
		    choose: function(datas){
		        start.max = datas; //结束日选好后，充值开始日的最大日期
		    }
		};
		laydate(start);
		laydate(end);
		
		//自定义日期格式
		laydate({
		    elem: '#test1',
		    format: 'YYYY年MM月DD日',
		    festival: true, //显示节日
		    choose: function(datas){ //选择日期完毕的回调
		        alert('得到：'+datas);
		    }
		});
		
		//日期范围限定在昨天到明天
		laydate({
		    elem: '#hello3',
		    min: laydate.now(-1), //-1代表昨天，-2代表前天，以此类推
		    max: laydate.now(+1) //+1代表明天，+2代表后天，以此类推
		});
		// 退出登录
		function exit() {
		    var date = new Date();
		    date.setTime(date.getTime() - 10000);
		    document.cookie = 'pp'    + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 'user'  + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 'puser' + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 'pec'   + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 's'     + "=" + null + "; expires=" + date.toGMTString();
		    document.cookie = 'fuser' + "=a; expires=" + date.toGMTString();
		    location.href='/login';
		}
	</script>
</html>